// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnzp03DR2buRRB3RvmyrQBUErzTEytDQ',
    appId: '1:1020055036371:web:564ad6e9942e208c850f26',
    messagingSenderId: '1020055036371',
    projectId: 'food-rescue-df06a',
    authDomain: 'food-rescue-df06a.firebaseapp.com',
    storageBucket: 'food-rescue-df06a.appspot.com',
    measurementId: 'G-10F4RV0WNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC88c2oIJF8UZkUMbD19cQTdy9oFSkYn4s',
    appId: '1:1020055036371:android:dd24427755c7952e850f26',
    messagingSenderId: '1020055036371',
    projectId: 'food-rescue-df06a',
    storageBucket: 'food-rescue-df06a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6XChEaPVMVZzOmrooufP5aOgm-PY_hw',
    appId: '1:1020055036371:ios:4715fa1301e6946c850f26',
    messagingSenderId: '1020055036371',
    projectId: 'food-rescue-df06a',
    storageBucket: 'food-rescue-df06a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6XChEaPVMVZzOmrooufP5aOgm-PY_hw',
    appId: '1:1020055036371:ios:4715fa1301e6946c850f26',
    messagingSenderId: '1020055036371',
    projectId: 'food-rescue-df06a',
    storageBucket: 'food-rescue-df06a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdnzp03DR2buRRB3RvmyrQBUErzTEytDQ',
    appId: '1:1020055036371:web:a3979d890d6e778d850f26',
    messagingSenderId: '1020055036371',
    projectId: 'food-rescue-df06a',
    authDomain: 'food-rescue-df06a.firebaseapp.com',
    storageBucket: 'food-rescue-df06a.appspot.com',
    measurementId: 'G-V9LF3NVQZE',
  );
}
